Working on create

diff --git a/digio b/digio
--- a/digio
+++ b/digio
@@ -128,7 +128,10 @@ API Actions.
 
   ${LIGHT_GREEN}create${NC}        ${DARK_GREY}- Create a new digitalocean droplet (by NAME)${NC}
   ${LIGHT_GREEN}delete${NC}        ${DARK_GREY}- Delete a new digitalocean droplet (by ID)${NC}
-  ${LIGHT_GREEN}list${NC}          ${DARK_GREY}- List all droplets (use this to grab your droplet IDs${NC}
+  ${LIGHT_GREEN}list <item>${NC}   ${DARK_GREY}- List all droplets (use this to grab your droplet IDs${NC}
+  ${LIGHT_GREEN}   droplets${NC}
+  ${LIGHT_GREEN}   droplets${NC}
+
 
 Other Actions
 
@@ -143,9 +146,33 @@ ${NC}
 "
 }
 
+do_help()
+{
+  case "$1" in
+  "create")
+    info "Create a new droplet..."
+    ;;
+  "list")
+    info "Show 'droplets' (default), and 'keys'."
+    ;;
+  *)
+    usage
+    ;;
+  esac
+}
+
 #--------------------
 # API CALLS
 #--------------------
+
+do_verify_token()
+{
+  if [[ "$1" = "" ]]; then
+    error "Please provide a digital ocean token, e.g. TOKEN=983339f14aaaxx94ex6xd49f17797af8f33fd9f39f8ff1xx74397ef83d791787"
+    error "For more information, please checkout https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-api-v2"
+    exit 1
+  fi
+}
 
 do_create()
 {
@@ -161,29 +188,13 @@ do_create()
   PRIVATE_NETWORKING=${PRIVATE_NETWORKING-true}
   LOGFILE=${LOGFILE-/tmp/digio.log}
 
-  if [[ "$TOKEN" = "" ]]; then
-    error "Please provide a digital ocean token, e.g. TOKEN=983339f14aaaxx94ex6xd49f17797af8f33fd9f39f8ff1xx74397ef83d791787"
-    error "For more information, please checkout https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-api-v2"
-    exit 1
-  fi
+  do_verify_token $TOKEN
 
   info "Creating a new droplet $NAME ($REGION, $SIZE, $IMAGE)"
 
   if [[ "$SSH_KEYS" = "default" ]]; then
-    RSA_PK=$HOME/.ssh/id_rsa.pub
-    DSA_PK=$HOME/.ssh/id_dsa.pub
-    PUBLIC_KEY=$RSA_PK
-    if [[ ! -e "$PUBLIC_KEY" ]]; then
-      PUBLIC_KEY=$DSA_PK
-    fi
-
-    if [[ ! -e "$PUBLIC_KEY" ]]; then
-      warn "  -- Unable to find your public in $RSA_PK or $DSA_PK, no SSH_KEYS provided"
-      SSH_KEYS="null"
-    else
-      debug " -- Providing you access to your droplet using $PUBLIC_KEY"
-      SSH_KEYS="[\"`cat $PUBLIC_KEY`\"]"
-    fi
+    error "Please provide your SSH_KEY 'ID', default not yet supported"
+    exit 1
   fi
 
   debug "  -- NAME=$NAME"
@@ -196,7 +207,7 @@ do_create()
   debug "  -- USER_DATA=$USER_DATA"
   debug "  -- PRIVATE_NETWORKING=$PRIVATE_NETWORKING"
   ANSWER=$(curl -X POST $DROPLET_URL \
-           -d "{\"name\":\"$NAME\", \"region\":\"$REGION\",\"size\":\"$SIZE\",\"image\":\"$IMAGE\", \"ssh_keys\": $SSH_KEYS, \"backups\": $BACKUPS, \"ipv6\": $IPV6, \"user_data\": $USER_DATA, \"private_networking\": $PRIVATE_NETWORKING}" \
+           -d "{\"name\":\"$NAME\", \"region\":\"$REGION\",\"size\":\"$SIZE\",\"image\":\"$IMAGE\", \"ssh_keys\": [ $SSH_KEYS ], \"backups\": $BACKUPS, \"ipv6\": $IPV6, \"user_data\": $USER_DATA, \"private_networking\": $PRIVATE_NETWORKING}" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" 2> $LOGFILE)
   if [ $? -ne 0 ] ; then
@@ -229,10 +240,42 @@ do_delete()
 
 do_list()
 {
+  do_verify_token $TOKEN
+  ITEM=${1-droplets}
+  debug "Looking up $ITEM"
+  case "$ITEM" in
+  "droplets")
+    do_ls_droplets
+    ;;
+  "keys")
+    do_ls_keys
+    ;;
+  esac
+}
+
+do_ls_droplets()
+{
   TOKEN=${TOKEN}
   LOGFILE=${LOGFILE-/tmp/digio.log}
 
   ANSWER=$(curl -X GET $DROPLET_URL \
+           -H "Authorization: Bearer $TOKEN" \
+           -H "Content-Type: application/json" 2> $LOGFILE)
+  if [ $? -ne 0 ] ; then
+    error "Unable to list droplets"
+    error "Reply: $ANSWER"
+    error_all $LOGFILE
+    exit 1
+  fi
+  info "$ANSWER"
+}
+
+do_ls_keys()
+{
+  TOKEN=${TOKEN}
+  LOGFILE=${LOGFILE-/tmp/digio.log}
+
+  ANSWER=$(curl -X GET $API_URL/account/keys \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" 2> $LOGFILE)
   if [ $? -ne 0 ] ; then
@@ -256,11 +299,10 @@ case "$1" in
   do_delete $2
   ;;
 "list")
-  do_list
+  do_list $2
   ;;
 "help")
-  usage
-  exit 0
+  do_help $2
   ;;
 "version")
   echo -e "${BLUE}DIGIO ${VERSION}${NC}"
