Simple JSON parsing of the results

diff --git a/dio b/dio
--- a/dio
+++ b/dio
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-VERSION=v0.10
+VERSION=v0.11
 API_URL=https://api.digitalocean.com/v2
 DROPLET_URL=$API_URL/droplets
 
@@ -44,8 +44,8 @@ FATAL_LEVEL=4
 
 error() { log $ERROR_LEVEL "${DARK_RED}$1${NC}"; }
 warn() { log $WARNING_LEVEL "${LIGHT_RED}$1${NC}"; }
-notify() { log $INFO_LEVEL "$1${NC}"; }
-info() { log $INFO_LEVEL "$1${NC}"; }
+notify() { log $INFO_LEVEL "${NC}$1${NC}"; }
+info() { log $INFO_LEVEL "${NC}$1${NC}"; }
 debug() { log $DEBUG_LEVEL "${LIGHT_GREY}$1${NC}"; }
 
 error_all() { [[ "$1" != "/dev/null" ]] && (tail -n 100 $1 > $1.last ; while read line; do error "$line" ; done < $1.last ;) }
@@ -152,7 +152,7 @@ Other Actions
 
 ${LIGHT_GREY}
 For reporting issues, please contact aforward@gmail.com, or
-reporting directly against the project at https://github.com/capbash/dio
+report directly against the project at https://github.com/capbash/dio
 ${NC}
 "
 }
@@ -172,40 +172,206 @@ do_help()
   esac
 }
 
-#--------------------
-# API CALLS
-#--------------------
-
-read_config()
-{
-  if [[ -e ".dio" ]]; then
-    debug "Reading in configs from .dio"
-    . .dio
-  else
-    debug "No .dio file, skippping"
-  fi
+throw () {
+  echo "$*" >&2
+  exit 1
 }
 
-do_verify_token()
+handle_error()
 {
-  if [[ "$1" = "" ]]; then
-    warn "\nWe were unable to find your Digital Ocean TOKEN, PLEASE TAKE ACTION BELOW.\n"
-    info "To provide you token you have have a few options...\n"
-    info "  1) Create a .dio config file and edit it to contain your token.\n"
-    info "     e.g. ${LIGHT_GREEN}dio init${NC}"
-    info "          ${LIGHT_GREEN}echo \"TOKEN=983339f14aaaxx94ex6xd89f17797af8f33fd9f39f8ff1xx74397ef83d791787\" >> .dio${NC}\n"
-    info "  2) Put your <TOKEN VALUE> in a TOKEN variable"
-    info "     e.g. ${LIGHT_GREEN}TOKEN=983339f14aaaxx94ex6xd89f17797af8f33fd9f39f8ff1xx74397ef83d791787 dio list keys${NC}"
-    info "\nIf you have no idea what we are talking about, please check out:"
-    info "   https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-api-v2"
-    info "\nPlease note that 983339f14aaaxx94ex6xd89f17797af8f33fd9f39f8ff1xx74397ef83d791787 is only an example,"
-    info "and your token will be much different"
-    info "\n"
+  local RETURN_CODE=$1
+  local ANSWER="$2"
+  local TITLE="$3"
+  local LOGFILE=${LOGFILE-/tmp/dio.log}
+  if [ $RETURN_CODE -ne 0 ] ; then
+    error $TITLE
+    OUTPUT=$(process "$ANSWER")
+    error "$OUTPUT"
+    error_all $LOGFILE
     exit 1
   fi
 }
 
-do_create()
+#--------------------
+# JSON PARSER
+#--------------------
+
+awk_egrep () {
+  local pattern_string=$1
+
+  gawk '{
+    while ($0) {
+      start=match($0, pattern);
+      token=substr($0, start, RLENGTH);
+      print token;
+      $0=substr($0, start+RLENGTH);
+    }
+  }' pattern="$pattern_string"
+}
+
+process()
+{
+  echo $1 | tokenize | parse
+}
+
+tokenize () {
+  local GREP
+  local ESCAPE
+  local CHAR
+
+  if echo "test string" | egrep -ao --color=never "test" &>/dev/null
+  then
+    GREP='egrep -ao --color=never'
+  else
+    GREP='egrep -ao'
+  fi
+
+  if echo "test string" | egrep -o "test" &>/dev/null
+  then
+    ESCAPE='(\\[^u[:cntrl:]]|\\u[0-9a-fA-F]{4})'
+    CHAR='[^[:cntrl:]"\\]'
+  else
+    GREP=awk_egrep
+    ESCAPE='(\\\\[^u[:cntrl:]]|\\u[0-9a-fA-F]{4})'
+    CHAR='[^[:cntrl:]"\\\\]'
+  fi
+
+  local STRING="\"$CHAR*($ESCAPE$CHAR*)*\""
+  local NUMBER='-?(0|[1-9][0-9]*)([.][0-9]*)?([eE][+-]?[0-9]*)?'
+  local KEYWORD='null|false|true'
+  local SPACE='[[:space:]]+'
+
+  $GREP "$STRING|$NUMBER|$KEYWORD|$SPACE|." | egrep -v "^$SPACE$"
+}
+
+parse_array () {
+  local index=0
+  local ary=''
+  read -r token
+  case "$token" in
+    ']') ;;
+    *)
+      while :
+      do
+        parse_value "$1" "$index"
+        index=$((index+1))
+        ary="$ary""$value"
+        read -r token
+        case "$token" in
+          ']') break ;;
+          ',') ary="$ary," ;;
+          *) throw "EXPECTED , or ] GOT ${token:-EOF}" ;;
+        esac
+        read -r token
+      done
+      ;;
+  esac
+  [ "$BRIEF" -eq 0 ] && value=$(printf '[%s]' "$ary") || value=
+  :
+}
+
+parse_object () {
+  local key
+  local obj=''
+  read -r token
+  case "$token" in
+    '}') ;;
+    *)
+      while :
+      do
+        case "$token" in
+          '"'*'"') key=$token ;;
+          *) throw "EXPECTED string GOT ${token:-EOF}" ;;
+        esac
+        read -r token
+        case "$token" in
+          ':') ;;
+          *) throw "EXPECTED : GOT ${token:-EOF}" ;;
+        esac
+        read -r token
+        parse_value "$1" "$key"
+        obj="$obj$key:$value"
+        read -r token
+        case "$token" in
+          '}') break ;;
+          ',') obj="$obj," ;;
+          *) throw "EXPECTED , or } GOT ${token:-EOF}" ;;
+        esac
+        read -r token
+      done
+    ;;
+  esac
+  [ "$BRIEF" -eq 0 ] && value=$(printf '{%s}' "$obj") || value=
+  :
+}
+
+parse_value () {
+  local jpath="${1:+$1,}$2" isleaf=0 isempty=0 print=0
+  case "$token" in
+    '{') parse_object "$jpath" ;;
+    '[') parse_array  "$jpath" ;;
+    # At this point, the only valid single-character tokens are digits.
+    ''|[!0-9]) throw "EXPECTED value GOT ${token:-EOF}" ;;
+    *) value=$token
+       # if asked, replace solidus ("\/") in json strings with normalized value: "/"
+       [ "$NORMALIZE_SOLIDUS" -eq 1 ] && value=${value//\\\//\/}
+       isleaf=1
+       [ "$value" = '""' ] && isempty=1
+       ;;
+  esac
+  [ "$value" = '' ] && return
+  [ "$LEAFONLY" -eq 0 ] && [ "$PRUNE" -eq 0 ] && print=1
+  [ "$LEAFONLY" -eq 1 ] && [ "$isleaf" -eq 1 ] && [ $PRUNE -eq 0 ] && print=1
+  [ "$LEAFONLY" -eq 0 ] && [ "$PRUNE" -eq 1 ] && [ "$isempty" -eq 0 ] && print=1
+  [ "$LEAFONLY" -eq 1 ] && [ "$isleaf" -eq 1 ] && \
+    [ $PRUNE -eq 1 ] && [ $isempty -eq 0 ] && print=1
+  [ "$print" -eq 1 ] && printf "[%s]\t%s\n" "$jpath" "$value"
+  :
+}
+
+parse () {
+  read -r token
+  parse_value
+  read -r token
+  case "$token" in
+    '') ;;
+    *) throw "EXPECTED EOF GOT $token" ;;
+  esac
+}
+
+BRIEF=1
+LEAFONLY=1
+PRUNE=1
+NORMALIZE_SOLIDUS=1
+
+
+#--------------------
+# API CALLS
+#--------------------
+
+lookup_droplets()
+{
+  local TOKEN=${TOKEN}
+  local LOGFILE=${LOGFILE-/tmp/dio.log}
+
+  local ANSWER=$(curl -X GET $DROPLET_URL \
+                 -H "Authorization: Bearer $TOKEN" \
+                 -H "Content-Type: application/json" 2> $LOGFILE)
+  echo $ANSWER
+}
+
+lookup_keys()
+{
+  local TOKEN=${TOKEN}
+  local LOGFILE=${LOGFILE-/tmp/dio.log}
+
+  local ANSWER=$(curl -X GET $API_URL/account/keys \
+                 -H "Authorization: Bearer $TOKEN" \
+                 -H "Content-Type: application/json" 2> $LOGFILE)
+  echo $ANSWER
+}
+
+action_create()
 {
   TOKEN=${TOKEN}
   NAME=$1
@@ -242,32 +408,58 @@ do_create()
            -d "{\"name\":\"$NAME\", \"region\":\"$REGION\",\"size\":\"$SIZE\",\"image\":\"$IMAGE\", $SSH_OUTPUT\"backups\": $BACKUPS, \"ipv6\": $IPV6, \"user_data\": $USER_DATA, \"private_networking\": $PRIVATE_NETWORKING}" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" 2> $LOGFILE)
-  if [ $? -ne 0 ] ; then
-    error "Unable to create droplet $NAME ($REGION, $SIZE, $IMAGE)"
-    error "Reply: $ANSWER"
-    error_all $LOGFILE
-    exit 1
-  fi
-  info "Reply: $ANSWER"
+
+  handle_error $? "$ANSWER" "Unable to create droplet $NAME ($REGION, $SIZE, $IMAGE)"
+  OUTPUT=$(process "$ANSWER")
+  OUTPUT=$(process "$ANSWER" | grep 'id\|name'  | grep -v 'kernel' | grep -v 'image' | grep -v 'region' | grep -v 'action' | awk -F' ' '{print $2}')
+
+  info "$OUTPUT"
 }
 
-do_delete()
+action_delete()
 {
-  ID=$1
-  TOKEN=${TOKEN}
-  LOGFILE=${LOGFILE-/tmp/dio.log}
+  local ID=$1
+  local TOKEN=${TOKEN}
+  local LOGFILE=${LOGFILE-/tmp/dio.log}
 
-  info "Deleting a droplet $ID"
-  ANSWER=$(curl -X DELETE $DROPLET_URL/$ID \
-           -H "Authorization: Bearer $TOKEN" \
-           -H "Content-Type: application/json" 2> $LOGFILE)
-  if [ $? -ne 0 ] ; then
-    error "Unable to delete droplet $ID"
-    error "Reply: $ANSWER"
-    error_all $LOGFILE
+  local ANSWER=$(curl -X DELETE $DROPLET_URL/$ID \
+                   -H "Authorization: Bearer $TOKEN" \
+                   -H "Content-Type: application/json" 2> $LOGFILE)
+
+  echo $ANSWER
+}
+
+#--------------------
+# TOOL CALLS
+#--------------------
+
+read_config()
+{
+  if [[ -e ".dio" ]]; then
+    debug "Reading in configs from .dio"
+    . .dio
+  else
+    debug "No .dio file, skippping"
+  fi
+}
+
+do_verify_token()
+{
+  if [[ "$1" = "" ]]; then
+    warn "\nWe were unable to find your Digital Ocean TOKEN, PLEASE TAKE ACTION BELOW.\n"
+    info "To provide you token you have have a few options...\n"
+    info "  1) Create a .dio config file and edit it to contain your token.\n"
+    info "     e.g. ${LIGHT_GREEN}dio init${NC}"
+    info "          ${LIGHT_GREEN}echo \"TOKEN=983339f14aaaxx94ex6xd89f17797af8f33fd9f39f8ff1xx74397ef83d791787\" >> .dio${NC}\n"
+    info "  2) Put your <TOKEN VALUE> in a TOKEN variable"
+    info "     e.g. ${LIGHT_GREEN}TOKEN=983339f14aaaxx94ex6xd89f17797af8f33fd9f39f8ff1xx74397ef83d791787 dio list keys${NC}"
+    info "\nIf you have no idea what we are talking about, please check out:"
+    info "   https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-api-v2"
+    info "\nPlease note that 983339f14aaaxx94ex6xd89f17797af8f33fd9f39f8ff1xx74397ef83d791787 is only an example,"
+    info "and your token will be much different"
+    info "\n"
     exit 1
   fi
-  info "Reply: $ANSWER"
 }
 
 do_list()
@@ -287,36 +479,38 @@ do_list()
 
 do_ls_droplets()
 {
-  TOKEN=${TOKEN}
-  LOGFILE=${LOGFILE-/tmp/dio.log}
+  ANSWER=$(lookup_droplets)
+  handle_error $? "$ANSWER" "Unable to list droplets"
+  OUTPUT=$(process "$ANSWER" | grep 'id\|name\|status' | grep -v 'kernel' | grep -v 'image' | grep -v 'region' | awk -F' ' '{print $2}')
 
-  ANSWER=$(curl -X GET $DROPLET_URL \
-           -H "Authorization: Bearer $TOKEN" \
-           -H "Content-Type: application/json" 2> $LOGFILE)
-  if [ $? -ne 0 ] ; then
-    error "Unable to list droplets"
-    error "Reply: $ANSWER"
-    error_all $LOGFILE
-    exit 1
-  fi
-  info "$ANSWER"
+  notify "\nAvailable Droplets:\n"
+  notify "$OUTPUT\n"
 }
 
 do_ls_keys()
 {
-  TOKEN=${TOKEN}
-  LOGFILE=${LOGFILE-/tmp/dio.log}
+  ANSWER=$(lookup_keys)
+  handle_error $? "$ANSWER" "Unable to list keys"
+  OUTPUT=$(process "$ANSWER" | grep 'id\|name' | awk -F' ' '{print $2}')
 
-  ANSWER=$(curl -X GET $API_URL/account/keys \
-           -H "Authorization: Bearer $TOKEN" \
-           -H "Content-Type: application/json" 2> $LOGFILE)
-  if [ $? -ne 0 ] ; then
-    error "Unable to list droplets"
-    error "Reply: $ANSWER"
-    error_all $LOGFILE
-    exit 1
+  notify "\nAvailable SSH Keys Include:\n"
+  notify "$OUTPUT\n"
+}
+
+do_delete()
+{
+  ID=$1
+
+  ANSWER=$(action_delete $ID)
+  handle_error $? "$ANSWER" "Unable to delete droplet $ID"
+
+  if [[ "$ANSWER" != "" ]]; then
+    OUTPUT=$(process "$ANSWER")
+    warn "\nUnable to delete droplet $ID, official message below..."
+    warn "  $ANSWER\n"
+  else
+    info "\nDeleted a droplet $ID\n"
   fi
-  info "$ANSWER"
 }
 
 do_init()
@@ -355,7 +549,7 @@ case "$1" in
   do_init
   ;;
 "create")
-  do_create $2
+  action_create $2
   ;;
 "delete")
   do_delete $2
